application:
    title: Spripng JPA Example
    version: 1.0.0
server:
    address: localhost
    port: 8081
spring:
    profiles:
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:3306/jpa?characterEncoding=UTF-8
        username: root
        password: kwic5539
    jpa:
        generate-ddl: true
        open-in-view: false
        hibernate:
            ddl-auto: update
        properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
            format_sql: true
            show_sql: true
            use_sql_comments: true
